/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package doan.hk.view;

import doan.hk.test.load;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class login2 extends javax.swing.JFrame {

    /**
     * Creates new form login2
     */
    public login2() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        taikhoan = new javax.swing.JTextField();
        matkhau = new javax.swing.JPasswordField();
        dnB = new javax.swing.JButton();
        rsB = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("TÀI KHOẢN");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 90, 20));

        jLabel3.setText("MẬT KHẨU");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, -1));
        getContentPane().add(taikhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 150, -1));
        getContentPane().add(matkhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 150, -1));

        dnB.setText("Đăng nhập");
        dnB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dnBActionPerformed(evt);
            }
        });
        getContentPane().add(dnB, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, -1, -1));

        rsB.setText("Đặt lại");
        rsB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rsBActionPerformed(evt);
            }
        });
        getContentPane().add(rsB, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC\\Pictures\\New folder\\1.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 500, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dnBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dnBActionPerformed
        // TODO add your handling code here:
        String user = taikhoan.getText();
       // nhập mk
       String password = new String(matkhau.getPassword());
       //tạo chuỗi động
       StringBuilder sb = new StringBuilder();
       if (user.equals("")){
             sb.append("Không được bỏ trống tài khoản. ");
       }
       if (password.equals("")){
             sb.append("Không được bỏ trống mật khẩu.  ");
       }
       if(sb.length()>0){
           JOptionPane.showMessageDialog(this,sb.toString(), "Invalidation",
                   JOptionPane.ERROR_MESSAGE);
       }
       if(user.equals("admin")&& password.equals("123")){
           JOptionPane.showMessageDialog(this, "Đăng nhập thành công. ");
                  // JOptionPane.ERROR_MESSAGE);
                  
//             quanliFrame qlF =  new quanliFrame();
//             qlF.show();
//             dispose();
               quanliFrame1 ql1 = new quanliFrame1();
               ql1.show();
               dispose();
       }else JOptionPane.showMessageDialog(this, "Tài khoản hoặc mật khẩu sai. ");
    }//GEN-LAST:event_dnBActionPerformed

    private void rsBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rsBActionPerformed
        // TODO add your handling code here:
        taikhoan.setText("");
        matkhau.setText("");
    }//GEN-LAST:event_rsBActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(login2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(login2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(login2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(login2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new login2().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dnB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField matkhau;
    private javax.swing.JButton rsB;
    private javax.swing.JTextField taikhoan;
    // End of variables declaration//GEN-END:variables
}
