/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package doan.hk.view;

import doan.hk.model.connectsql1;
import doan.hk.model.ttc2;
import doan.hk.model.ttc2Dao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author PC
 */
public class ttc2Frame1 extends javax.swing.JFrame {
   
    /**
     * Creates new form ttc2Frame
     */
 //   final String header[] = {};
     public  void xoaTrang(){
       mahsTf.setText("");
       tenTf.setText("");
       tc2Tf.setText("");
       hl6.setText("");
       hk6.setText("");
       dtb6.setText("");
       hl7.setText("");
       hk7.setText("");
       dtb7.setText("");
       hl8.setText("");
       hk8.setText("");
       dtb8.setText("");
       hl9.setText("");
       hk9.setText("");
       dtb9.setText("");
    }
    public ttc2Frame1() {
        initComponents();
        setLocationRelativeTo(null);
        try{
           connectsql1 cns = new connectsql1();
           Connection con = cns.getConnection();
          //Connection con = DriverManager.getConnection("jdbc:sqlserver://LAPTOP-VQ8FO7NU\\SQLEXPRESS:1433;" + "user=sa;password=123;databaseName=DoanQLTS;encrypt=false");
          PreparedStatement pst = con.prepareStatement("Select * from ttc2");
          ResultSet rs = pst.executeQuery();
          DefaultTableModel model = (DefaultTableModel)ttTable.getModel();
          while(rs.next()){
             Object objList[] = {rs.getString("maHoSo"),rs.getString("Ten"), rs.getString("Truong")
                 ,rs.getString("HL6"),rs.getString("HK6"), rs.getFloat("DTB6"), 
                 rs.getString("HL7"),rs.getString("HK7"), rs.getFloat("DTB7"),
                 rs.getString("HL8"),rs.getString("HK8"), rs.getFloat("DTB8"),
                     rs.getString("HL9"),rs.getString("HK9"), rs.getFloat("DTB9")  
             };
             model.addRow(objList);
           //  con.close();
          }
        }catch(SQLException ex){
                     Logger.getLogger(ttc2Frame1.class.getName()).log(Level.SEVERE, null, ex);
         }
//        if(ttTable.getSelectedRow()>= 0){
//           mahsTf.getText(ttTable.getValueAt(ttTable.getSelectedRow(), 0)+"");
//        }
        ttTable.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if(ttTable.getSelectedRow()>=0 ){
                  mahsTf.setText(ttTable.getValueAt(ttTable.getSelectedRow(), 0)+ "");
                  tenTf.setText(ttTable.getValueAt(ttTable.getSelectedRow(), 1)+ "");
                  tc2Tf.setText(ttTable.getValueAt(ttTable.getSelectedRow(), 2)+ "");
                  hl6.setText(ttTable.getValueAt(ttTable.getSelectedRow(), 3)+ "");
                  hk6.setText(ttTable.getValueAt(ttTable.getSelectedRow(), 4)+ "");
                  dtb6.setText(ttTable.getValueAt(ttTable.getSelectedRow(), 5)+ "");
                  hl7.setText(ttTable.getValueAt(ttTable.getSelectedRow(), 6)+ "");
                  hk7.setText(ttTable.getValueAt(ttTable.getSelectedRow(), 7)+ "");
                  dtb7.setText(ttTable.getValueAt(ttTable.getSelectedRow(), 8)+ "");
                  hl8.setText(ttTable.getValueAt(ttTable.getSelectedRow(), 9)+ "");
                  hk8.setText(ttTable.getValueAt(ttTable.getSelectedRow(), 10)+ "");
                  dtb8.setText(ttTable.getValueAt(ttTable.getSelectedRow(), 11)+ "");
                  hl9.setText(ttTable.getValueAt(ttTable.getSelectedRow(), 12)+ "");
                  hk9.setText(ttTable.getValueAt(ttTable.getSelectedRow(), 13)+ "");
                  dtb9.setText(ttTable.getValueAt(ttTable.getSelectedRow(), 14)+ "");
                }
            }
        });
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ttTable = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        mahsTf = new javax.swing.JTextField();
        tenTf = new javax.swing.JTextField();
        tc2Tf = new javax.swing.JTextField();
        hl6 = new javax.swing.JTextField();
        hk6 = new javax.swing.JTextField();
        dtb6 = new javax.swing.JTextField();
        hl7 = new javax.swing.JTextField();
        hk7 = new javax.swing.JTextField();
        dtb7 = new javax.swing.JTextField();
        hl8 = new javax.swing.JTextField();
        hk8 = new javax.swing.JTextField();
        dtb8 = new javax.swing.JTextField();
        hl9 = new javax.swing.JTextField();
        hk9 = new javax.swing.JTextField();
        dtb9 = new javax.swing.JTextField();
        addBt = new javax.swing.JButton();
        editBt = new javax.swing.JButton();
        dltBt = new javax.swing.JButton();
        qlBtn = new javax.swing.JButton();
        timBT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 19, Short.MAX_VALUE)
        );

        jLabel2.setText("Mã hồ sơ");

        jLabel3.setText("Tên học sinh");

        jLabel4.setText("Trường cấp 2");

        jLabel5.setText("Học lực lớp 6");

        jLabel6.setText("Hạnh kiểm lớp 6");

        jLabel7.setText("Điểm TB lớp 6");

        jLabel8.setText("Hạnh kiểm lớp 7");

        jLabel9.setText("Hạnh kiểm lớp 7");

        jLabel10.setText("Điểm TB lớp 7");

        ttTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã hồ sơ", "Tên học sinh", "Trường cấp 2", "HL6", "HK6", "ĐTB6", "HL7", "HK7", "ĐTB7", "HL8", "HK8", "ĐTB8", "HL9", "HK9", "ĐTB9"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, true, true, true, true, true, true, true, true, true, true, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(ttTable);

        jLabel11.setText("Học lực lớp 8");

        jLabel12.setText("Hạnh kiểm lớp 8");

        jLabel13.setText("Điểm TB lớp 8");

        jLabel14.setText("Học lực lớp 9");

        jLabel16.setText("Điểm TB lớp 8");

        jLabel17.setText("Hạnh kiểm lớp 9");

        tc2Tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tc2TfActionPerformed(evt);
            }
        });

        hl6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hl6ActionPerformed(evt);
            }
        });

        dtb6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dtb6ActionPerformed(evt);
            }
        });

        addBt.setText("Thêm");
        addBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtActionPerformed(evt);
            }
        });

        editBt.setText("Sửa");
        editBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtActionPerformed(evt);
            }
        });

        dltBt.setText("Xóa");
        dltBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dltBtActionPerformed(evt);
            }
        });

        qlBtn.setText("Quay lại");
        qlBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qlBtnActionPerformed(evt);
            }
        });

        timBT.setText("Tìm");
        timBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timBTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tenTf, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tc2Tf, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hl6, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hk7, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE))
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(hk6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dtb6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dtb7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                .addGap(133, 133, 133)
                                .addComponent(hl7, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(mahsTf, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addBt, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(timBT)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(dltBt, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(qlBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(editBt)
                                        .addGap(79, 79, 79))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(hl8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                                        .addComponent(hk8, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(dtb8, javax.swing.GroupLayout.Alignment.TRAILING))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dtb9, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(hk9, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                                        .addComponent(hl9)))))
                        .addGap(29, 29, 29))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(mahsTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hl8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(timBT))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tenTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hk8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tc2Tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dtb8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(hl6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hl9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel17)
                    .addComponent(hk6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hk9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel16)
                    .addComponent(dtb6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dtb9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(hl7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addBt)
                            .addComponent(editBt))
                        .addGap(3, 3, 3)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(hk7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(dtb7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qlBtn)
                    .addComponent(dltBt))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dtb6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dtb6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dtb6ActionPerformed

    private void tc2TfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tc2TfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tc2TfActionPerformed

    private void hl6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hl6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hl6ActionPerformed

    private void qlBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qlBtnActionPerformed
        // TODO add your handling code here:
         quanliFrame1 qlf1 = new quanliFrame1();
         qlf1.show();
         dispose();
    }//GEN-LAST:event_qlBtnActionPerformed

    private void addBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtActionPerformed
        // TODO add your handling code here:
        try{
        if (mahsTf.getText().equals("")|| tenTf.getText().equals("")|| tc2Tf.getText().equals("")||
                hl6.getText().equals("")|| hk6.getText().equals("") || dtb6 .getText().equals("") ||
                hl7.getText().equals("")|| hk7.getText().equals("") || dtb7 .getText().equals("") ||
                hl8.getText().equals("")|| hk8.getText().equals("") || dtb8 .getText().equals("") ||
                hl9.getText().equals("")|| hk9.getText().equals("") || dtb9 .getText().equals("") ){
            JOptionPane.showMessageDialog(this, "Hãy nhập đủ dữ liệu");
        }
        else{
            connectsql1 cns = new connectsql1();
            Connection conn = cns.getConnection();
            // khóa chính
             StringBuilder sb = new StringBuilder();
             String sql_check_pk = "Select MaHoSo from ttc2 where MaHoSo ='"+ mahsTf.getText()+  "' ";
             java.sql.Statement st = conn.createStatement();
             ResultSet rs = st.executeQuery(sql_check_pk);
             if(rs.next()){
                  sb.append("Hồ sơ đã tồn tại.");
             }
              if(sb.length() > 0){
                   JOptionPane.showMessageDialog(this, "Hồ sơ đã tồn tại");
                 
                }else {
                        try{
                       ttc2 tt = new ttc2();
                       tt.setMaHoSo(mahsTf.getText());
                       tt.setTenHS(tenTf.getText());
                       tt.setTenTruong(tc2Tf.getText());
                       tt.setHL6(hl6.getText());
                       tt.setHK6(hk6.getText());
                       tt.setDtb6(dtb6.getText());
                       tt.setHL7(hl7.getText());
                       tt.setHK7(hk7.getText());
                       tt.setDtb7(dtb7.getText());
                       tt.setHL8(hl8.getText());
                       tt.setHK8(hk8.getText());
                       tt.setDtb8(dtb8.getText());
                       tt.setHL9(hl9.getText());
                       tt.setHK9(hk9.getText());
                       tt.setDtb9(dtb9.getText());
                       ttc2Dao ttDao = new ttc2Dao();
                       ttDao.insert(tt);
                       xoaTrang();
                      JOptionPane.showMessageDialog(this, "Thêm thành công");
                      ttc2Frame1 tF = new ttc2Frame1();
        tF.show();
        dispose();
                        } catch (Exception e ){
                          JOptionPane.showMessageDialog(this, "Errol: "+ e.getMessage());
                           e.printStackTrace();
                        }
                    }
        
           }
        }catch(Exception e){
            
        // e.printStackTrace();
        }
        
    }//GEN-LAST:event_addBtActionPerformed

    private void timBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timBTActionPerformed
        // TODO add your handling code here:
        if(mahsTf.getText().equals("")){
          JOptionPane.showMessageDialog(this, "Bạn cần nhập mã hồ sơ cần tìm. ");
          return;
        }
        
        try {
            
            ttc2Dao ttDao = new ttc2Dao();
            ttc2 Ttc2 = ttDao.searchById(mahsTf.getText());
           
            if(Ttc2 != null){//nếu tìm thấy set các giá trị vào ô text
                
                mahsTf.setText(Ttc2.getMaHoSo());
                tenTf.setText(Ttc2.getTenHS());
                tc2Tf.setText(Ttc2.getTenTruong());
                hl6.setText(Ttc2.getHL6());
                hk6.setText(Ttc2.getHK6());
                dtb6.setText(Ttc2.getDtb6());
                hl7.setText(Ttc2.getHL7());
                hk7.setText(Ttc2.getHK7());
                dtb7.setText(Ttc2.getDtb7());
                hl8.setText(Ttc2.getHL8());
                hk8.setText(Ttc2.getHK8());
                dtb8.setText(Ttc2.getDtb8()); 
                hl9.setText(Ttc2.getHL9());
                hk9.setText(Ttc2.getHK9());
                dtb9.setText(Ttc2.getDtb9());
            }else JOptionPane.showMessageDialog(this, "Không tìm thấy hồ sơ");
        } catch (Exception e) {
             JOptionPane.showMessageDialog(this, "Error: "+e.getMessage());
                  e.printStackTrace();
        }
    }//GEN-LAST:event_timBTActionPerformed

    private void editBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtActionPerformed
        // TODO add your handling code here:
        StringBuilder sb = new StringBuilder();
        if(mahsTf.getText().equals("")|| tenTf.getText().equals("")|| tc2Tf.getText().equals("")||
                hl6.getText().equals("")|| hk6.getText().equals("") || dtb6 .getText().equals("") ||
                hl7.getText().equals("")|| hk7.getText().equals("") || dtb7 .getText().equals("") ||
                hl8.getText().equals("")|| hk8.getText().equals("") || dtb8 .getText().equals("") ||
                hl9.getText().equals("")|| hk9.getText().equals("") || dtb9 .getText().equals("") ){
            JOptionPane.showMessageDialog(this,"Hãy nhập đủ dữ liệu. ");
        }else{
        if(sb.length()>0){
         JOptionPane.showMessageDialog(this, sb.toString());
        }
        
        try{
          ttc2 ttc2 = new ttc2();
                  ttc2.setMaHoSo(mahsTf.getText());
                  ttc2.setTenHS(tenTf.getText());
                  ttc2.setTenTruong(tc2Tf.getText());
                  ttc2.setHL6(hl6.getText());
                  ttc2.setHK6(hk6.getText());
                  ttc2.setDtb6(dtb6.getText());
                  ttc2.setHL7(hl7.getText());
                  ttc2.setHK7(hk7.getText());
                  ttc2.setDtb7(dtb7.getText());
                  ttc2.setHL8(hl8.getText());
                  ttc2.setHK8(hk8.getText());
                  ttc2.setDtb8(dtb8.getText());
                  ttc2.setHL9(hl9.getText());
                  ttc2.setHK9(hk9.getText());
                  ttc2.setDtb9(dtb9.getText());
             ttc2Dao ttc2Dao = new ttc2Dao();
             
             ttc2Dao.upDate(ttc2);
             JOptionPane.showMessageDialog(this, "Cập nhật thành công");
             ttc2Frame1 tF = new ttc2Frame1();
        tF.show();
        dispose();
        }
        
        catch(Exception e){
           JOptionPane.showMessageDialog(this, "Errol: "+ e.getMessage());
           e.printStackTrace();
        }
        } 
    }//GEN-LAST:event_editBtActionPerformed

    private void dltBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dltBtActionPerformed
        // TODO add your handling code here:
        StringBuilder sb = new StringBuilder();
        if(mahsTf.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Hãy nhập mã hồ sơ cần xóa. ");
        }else{
        if(sb.length()>0){
         JOptionPane.showMessageDialog(this, sb.toString());
        }
        
        try{
            ttc2Dao ttc2Dao = new ttc2Dao();
            ttc2Dao.delete(mahsTf.getText());
             JOptionPane.showMessageDialog(this, "Xóa thành công. ");
             ttc2Frame1 tF = new ttc2Frame1();
        tF.show();
        dispose();
        }catch(Exception e){
           JOptionPane.showMessageDialog(this, "Errol: "+ e.getMessage());
           e.printStackTrace();
        }
        }
    }//GEN-LAST:event_dltBtActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ttc2Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ttc2Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ttc2Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ttc2Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ttc2Frame1().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBt;
    private javax.swing.JButton dltBt;
    private javax.swing.JTextField dtb6;
    private javax.swing.JTextField dtb7;
    private javax.swing.JTextField dtb8;
    private javax.swing.JTextField dtb9;
    private javax.swing.JButton editBt;
    private javax.swing.JTextField hk6;
    private javax.swing.JTextField hk7;
    private javax.swing.JTextField hk8;
    private javax.swing.JTextField hk9;
    private javax.swing.JTextField hl6;
    private javax.swing.JTextField hl7;
    private javax.swing.JTextField hl8;
    private javax.swing.JTextField hl9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField mahsTf;
    private javax.swing.JButton qlBtn;
    private javax.swing.JTextField tc2Tf;
    private javax.swing.JTextField tenTf;
    private javax.swing.JButton timBT;
    private javax.swing.JTable ttTable;
    // End of variables declaration//GEN-END:variables
}
